---
initial_load_eq: ''
manual_load: ''
bucket: bigquery_assignment__test         #Bucket to write table to
datalake_path: tables/austin_bikeshare/   #Folder to write table to
datalake_tables: bikeshare_trips          #Table to load
bigquery_dataset_name: austin_bikeshare   #BigQuery dataset name
cluster_config:                           #COnfiguration for dataproc cluster
  gce_cluster_config:
    internal_ip_only: 0
    service_account: 
  master_config:
    num_instances: 1
    machine_type_uri: n1-standard-4
    disk_config:
      boot_disk_type: pd-standard
      boot_disk_size_gb: 32
  worker_config:
    num_instances: 2
    machine_type_uri: n1-standard-4
    disk_config:
      boot_disk_type: pd-standard
      boot_disk_size_gb: 32
bigquery_tables:                          #List of BigQuery tables to create and their schemas
  bikeshare_trips:
  - name: trip_id
    mode: NULLABLE
    type: STRING
    description: ''
    fields: []
  - name: subscriber_type
    mode: NULLABLE
    type: STRING
    description: ''
    fields: []
  - name: bike_id
    mode: NULLABLE
    type: STRING
    description: ''
    fields: []
  - name: bike_type
    mode: NULLABLE
    type: STRING
    description: ''
    fields: []
  - name: start_time
    mode: NULLABLE
    type: TIMESTAMP
    description: ''
    fields: []
  - name: start_station_id
    mode: NULLABLE
    type: INTEGER
    description: ''
    fields: []
  - name: start_station_name
    mode: NULLABLE
    type: STRING
    description: ''
    fields: []
  - name: end_station_id
    mode: NULLABLE
    type: STRING
    description: ''
    fields: []
  - name: end_station_name
    mode: NULLABLE
    type: STRING
    description: ''
    fields: []
  - name: duration_minutes
    mode: NULLABLE
    type: INTEGER
    description: ''
    fields: []
